quarkus:
  mongodb:
    connection-string: mongodb+srv://davidcb:${MONGO_PASSWORD}@home-cluster.128tt5d.mongodb.net/?retryWrites=true&w=majority
    database: iot-data
  micrometer:
    export:
      stackdriver:
        default-registry: false
    binder-enabled-default: false
