package org.davidcb.iotdatahandler.infrastructure.adapters.outward.temperature

import io.quarkus.mongodb.panache.reactive.ReactivePanacheMongoRepository
import org.davidcb.iotdatahandler.infrastructure.adapters.outward.temperature.entities.TemperatureEntity
import javax.enterprise.context.ApplicationScoped

@ApplicationScoped
class TemperatureRepository : ReactivePanacheMongoRepository<TemperatureEntity>
